image: registry.gitlab.dev-o-sud.fr/public-devosud/docker-images/nodejs:latest

cache:
  untracked: true
  paths:
    - node_modules/
    - dist/

stages:
  - build
  - test
  - deploy


build:
  stage: build
  script:
    - npm install
    - sed -i "s/0.0.0/`git describe`/g" package.json
    - cat package.json
    - ng build --prod
  tags:
    - nodeJS

test:
  stage: test
  script:
    - ng test
  tags:
    - nodeJS
  allow_failure: true

deploy:
  stage: deploy
  script:
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  only:
    - master
  tags:
    - nodeJS
