version: '3'
services:
  frontend:
    networks:
      - net_app
    build: .
    volumes:
      - .:/myapp
    ports:
      - "4200:4200"
    container_name: angular
networks:
  net_app:
      driver: bridge
