version: 2
jobs:
  build:
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Install chromium
          command: 'sudo apt install chromium'
      - run:
          name: Set chromium ENV
          command: 'export CHROME_BIN=/usr/bin/chromium'
      - run:
          xvfb-run -a npm test
