version: 2
jobs:
  build:
    environment:
      CHROME_BIN: /usr/bin/chromium
    docker:
      - image: vareversat/angular:latest
    steps:
      - checkout
      - run:
          name: Install npm
          command: 'npm install'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lauch integration tests
          command: ng test
      - run:
          name: Build for production
          command: ng build --prod
      - run:
          name: Netlify Deploy
          command: netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=dist/resume
